openapi: 3.1.0
x-stoplight:
  id: 32pxuah6hmb9a
info:
  title: Codat - Commerce API
  version: '1.0'
  summary: 'Codat''s standardized API for accessing commerce data '
  contact:
    name: Codat
    url: 'https://codat.io'
    email: support@codat.io
  description: Codat's commerce api allows you to access standardised data from over 10 commerce and POS systems.
  termsOfService: 'https://www.codat.io/msa/'
servers:
  - url: 'https://api.codat.io'
    description: Codat
tags:
  - name: Commerce Data
    description: Retrieve standardized data from linked commerce platforms.
paths:
  '/companies/{companyId}/connections/{connectionId}/data/commerce-customers':
    parameters:
      - $ref: ./Codat-Common.yaml#/components/parameters/companyId
      - $ref: ./Codat-Common.yaml#/components/parameters/connectionId
    get:
      summary: List customers
      tags:
        - Commerce Data
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                allOf:
                  - type: object
                    properties:
                      results:
                        type: array
                        items:
                          $ref: ./Commerce/Customer.yaml
                  - $ref: ./Codat-Common.yaml#/components/schemas/_Links
              examples:
                example-1:
                  value:
                    results:
                      - id: 13d946f0-c5d5-42bc-b092-97ece17923ab
                        amount: 194.12
                        currency: GBP
                        paymentMethodRef:
                          id: EILBDVJVNUAGVKRQ
                          name: AliPay
                        status: Pending
                        paymentProvider: Amazon Pay
                        dueDate: '2019-08-24T14:15:22Z'
                        createdDate: '2019-08-24T14:15:22Z'
                        modifiedDate: '2019-08-24T14:15:22Z'
                        sourceModifiedDate: '2019-08-24T14:15:22Z'
                    _links:
                      self:
                        href: ../dictionary
                      current:
                        href: ../dictionary
                      next:
                        href: ../dictionary
                      previous:
                        href: ../dictionary
                    pageNumber: 0
                    pageSize: 0
                    totalResults: 0
      operationId: list-commerce-customers
      description: List all commerce customers for the given company and data connection
      parameters:
        - $ref: ./Codat-Common.yaml#/components/parameters/page
        - $ref: ./Codat-Common.yaml#/components/parameters/pageSize
        - $ref: ./Codat-Common.yaml#/components/parameters/query
        - $ref: ./Codat-Common.yaml#/components/parameters/orderBy
  '/companies/{companyId}/connections/{connectionId}/data/commerce-disputes':
    parameters:
      - $ref: ./Codat-Common.yaml#/components/parameters/companyId
      - $ref: ./Codat-Common.yaml#/components/parameters/connectionId
    get:
      summary: List disputes
      tags:
        - Commerce Data
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                allOf:
                  - type: object
                    properties:
                      results:
                        type: array
                        items:
                          $ref: ./Commerce/DIspute.yaml
                  - $ref: ./Codat-Common.yaml#/components/schemas/_Links
              examples:
                Example:
                  value:
                    results:
                      - id: 13d946f0-c5d5-42bc-b092-97ece17923ab
                        disputedTransactions:
                          id: 13d946f0-c5d5-42bc-b092-97ece17923ab
                          type: Fee
                        totalAmount: 194.12
                        currency: GBP
                        status: Won
                        reason: Unhappy with product
                        dueDate: '2021-03-29T14:39:55'
                        createdDate: '2019-08-24T14:15:22Z'
                        modifiedDate: '2019-08-24T14:15:22Z'
                        sourceModifiedDate: '2019-08-24T14:15:22Z'
                    _links:
                      self:
                        href: ../dictionary
                      current:
                        href: ../dictionary
                      next:
                        href: ../dictionary
                      previous:
                        href: ../dictionary
                    pageNumber: 0
                    pageSize: 0
                    totalResults: 0
      operationId: list-commerce-disputes
      description: List commerce disputes
      parameters:
        - $ref: ./Codat-Common.yaml#/components/parameters/page
        - $ref: ./Codat-Common.yaml#/components/parameters/pageSize
        - $ref: ./Codat-Common.yaml#/components/parameters/query
        - $ref: ./Codat-Common.yaml#/components/parameters/orderBy
  '/companies/{companyId}/connections/{connectionId}/data/commerce-info':
    parameters:
      - $ref: ./Codat-Common.yaml#/components/parameters/companyId
      - $ref: ./Codat-Common.yaml#/components/parameters/connectionId
    get:
      summary: Get company info
      tags:
        - Commerce Data
      responses: {}
      operationId: get-commerce-info
      description: |-
        Retrieve information about the company, as seen in the commerce platform.

        This may include information like addresses, tax registration details and social media or website information.
      requestBody:
        content:
          application/json:
            schema:
              $ref: ./Commerce/CompanyInfo.yaml
            examples:
              Example:
                value:
                  companyName: Codat
                  commercePlatformRef: string
                  companyLegalName: Codat Limited
                  addresses:
                    - type: Billing
                      line1: string
                      line2: string
                      city: string
                      region: string
                      country: string
                      postalCode: string
                  phoneNumbers:
                    - number: +44 25691 154789
                      type: Primary
                  webLinks:
                    - type: Website
                      url: 'https://codat.io'
                  registrationNumber: '10480375'
                  baseCurrency: GBP
                  accountBalances:
                    - available: 0
                      pending: 0
                      reserved: 0
                      currency: GBP
                  sourceUrls:
                    url1: 'https://connect.sandbox.com/v2/customers'
                    url2: 'https://connect.sandbox.com/v2/disputes'
                  createdDate: '2019-08-24T14:15:22Z'
                  modifiedDate: '2019-08-24T14:15:22Z'
                  sourceModifiedDate: '2019-08-24T14:15:22Z'
  '/companies/{companyId}/connections/{connectionId}/data/commerce-locations':
    parameters:
      - $ref: ./Codat-Common.yaml#/components/parameters/companyId
      - $ref: ./Codat-Common.yaml#/components/parameters/connectionId
    get:
      summary: List locations
      tags:
        - Commerce Data
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                allOf:
                  - type: object
                    properties:
                      results:
                        type: array
                        items:
                          $ref: ./Commerce/Locations.yaml
                  - $ref: ./Codat-Common.yaml#/components/schemas/_Links
              examples:
                Example:
                  value:
                    results:
                      - id: 13d946f0-c5d5-42bc-b092-97ece17923ab
                        name: string
                        address:
                          type: Billing
                          line1: string
                          line2: string
                          city: string
                          region: string
                          country: string
                          postalCode: string
                        modifiedDate: '2019-08-24T14:15:22Z'
                        sourceModifiedDate: '2019-08-24T14:15:22Z'
                    _links:
                      self:
                        href: ../dictionary
                      current:
                        href: ../dictionary
                      next:
                        href: ../dictionary
                      previous:
                        href: ../dictionary
                    pageNumber: 0
                    pageSize: 0
                    totalResults: 0
      operationId: list-commerce-locations
      description: |-
        Retrieve a list of locations as seen in the commerce platform.

        A `location` is a geographic place at which stocks of products may be held, or from where orders were placed.
  '/companies/{companyId}/connections/{connectionId}/data/commerce-orders':
    parameters:
      - $ref: ./Codat-Common.yaml#/components/parameters/companyId
      - $ref: ./Codat-Common.yaml#/components/parameters/connectionId
    get:
      summary: List orders
      tags:
        - Commerce Data
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                allOf:
                  - type: object
                    properties:
                      results:
                        type: array
                        items:
                          $ref: ./Commerce/Order.yaml
                  - $ref: ./Codat-Common.yaml#/components/schemas/_Links
      operationId: list-commerce-orders
      description: Get a list of orders placed or held on the linked commerce platform
      parameters:
        - $ref: ./Codat-Common.yaml#/components/parameters/page
        - $ref: ./Codat-Common.yaml#/components/parameters/pageSize
        - $ref: ./Codat-Common.yaml#/components/parameters/query
        - $ref: ./Codat-Common.yaml#/components/parameters/orderBy
  '/companies/{companyId}/connections/{connectionId}/data/commerce-payments':
    parameters:
      - $ref: ./Codat-Common.yaml#/components/parameters/companyId
      - $ref: ./Codat-Common.yaml#/components/parameters/connectionId
    get:
      summary: List payments
      tags:
        - Commerce Data
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                allOf:
                  - type: object
                    properties:
                      results:
                        type: array
                        items:
                          $ref: ./Commerce/Payment.yaml
                  - $ref: ./Codat-Common.yaml#/components/schemas/_Links
      operationId: list-commerce-payments
      description: List commerce payments for the given company & data connection.
      parameters:
        - $ref: ./Codat-Common.yaml#/components/parameters/page
        - $ref: ./Codat-Common.yaml#/components/parameters/pageSize
        - $ref: ./Codat-Common.yaml#/components/parameters/query
        - $ref: ./Codat-Common.yaml#/components/parameters/orderBy
  '/companies/{companyId}/connections/{connectionId}/data/commerce-paymentMethods':
    parameters:
      - $ref: ./Codat-Common.yaml#/components/parameters/companyId
      - $ref: ./Codat-Common.yaml#/components/parameters/connectionId
    get:
      summary: List payment methods
      tags:
        - Commerce Data
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                allOf:
                  - type: object
                    properties:
                      results:
                        type: array
                        items:
                          $ref: ./Commerce/PaymentMethod.yaml
                  - $ref: ./Codat-Common.yaml#/components/schemas/_Links
      operationId: list-commerce-paymentMethods
      description: 'Retrieve a list of payment methods, such as card, cash or other online payment methods, as held in the linked commerce platform.'
      parameters:
        - $ref: ./Codat-Common.yaml#/components/parameters/page
        - $ref: ./Codat-Common.yaml#/components/parameters/pageSize
        - $ref: ./Codat-Common.yaml#/components/parameters/query
        - $ref: ./Codat-Common.yaml#/components/parameters/orderBy
  '/companies/{companyId}/connections/{connectionId}/data/commerce-products':
    parameters:
      - $ref: ./Codat-Common.yaml#/components/parameters/companyId
      - $ref: ./Codat-Common.yaml#/components/parameters/connectionId
    get:
      summary: List products
      tags:
        - Commerce Data
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                allOf:
                  - type: object
                    properties:
                      results:
                        type: array
                        items:
                          $ref: ./Commerce/Product.yaml
                  - $ref: ./Codat-Common.yaml#/components/schemas/_Links
      operationId: list-commerce-products
      parameters:
        - $ref: ./Codat-Common.yaml#/components/parameters/page
        - $ref: ./Codat-Common.yaml#/components/parameters/pageSize
        - $ref: ./Codat-Common.yaml#/components/parameters/query
        - $ref: ./Codat-Common.yaml#/components/parameters/orderBy
      description: 'The Products data type provides the company''s product inventory, and includes the price and quantity of all products, and product variants, available for sale.'
  '/companies/{companyId}/connections/{connectionId}/data/commerce-transactions':
    parameters:
      - $ref: ./Codat-Common.yaml#/components/parameters/companyId
      - $ref: ./Codat-Common.yaml#/components/parameters/connectionId
    get:
      summary: List transactions
      tags:
        - Commerce Data
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                allOf:
                  - type: object
                    properties:
                      results:
                        type: array
                        items:
                          $ref: ./Commerce/Transaction.yaml
                  - $ref: ./Codat-Common.yaml#/components/schemas/_Links
      operationId: list-commerce-transactions
      description: 'Details of all financial transactions recorded in the commerce or point of sale system are added to the Transactions data type. For example, payments, service charges, and fees.'
      parameters:
        - $ref: ./Codat-Common.yaml#/components/parameters/page
        - $ref: ./Codat-Common.yaml#/components/parameters/pageSize
        - $ref: ./Codat-Common.yaml#/components/parameters/query
        - $ref: ./Codat-Common.yaml#/components/parameters/orderBy
  '/companies/{companyId}/connections/{connectionId}/data/commerce-productCategories':
    parameters:
      - $ref: ./Codat-Common.yaml#/components/parameters/companyId
      - $ref: ./Codat-Common.yaml#/components/parameters/connectionId
    get:
      summary: List product categories
      tags:
        - Commerce Data
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                allOf:
                  - type: object
                    properties:
                      results:
                        type: array
                        items:
                          $ref: ./Commerce/ProductCategory.yaml
                  - $ref: ./Codat-Common.yaml#/components/schemas/_Links
      operationId: list-commerce-productCategories
      parameters:
        - $ref: ./Codat-Common.yaml#/components/parameters/page
        - $ref: ./Codat-Common.yaml#/components/parameters/pageSize
        - $ref: ./Codat-Common.yaml#/components/parameters/query
        - $ref: ./Codat-Common.yaml#/components/parameters/orderBy
      description: 'Product categories are used to classify a group of products together, either by type (eg "Furniture"), or sometimes by tax profile.'
components:
  schemas: {}
  securitySchemes:
    Authorization:
      name: Your Base 64 encoded API Key
      type: apiKey
      in: header
security:
  - Authorization: []
